syntax = "proto3";

option csharp_namespace = "FeatureManagementExperimentation.Grpc";

package FmeApi;

// The FME service definition.
service Fme {
  // Evaluates a feature flag
  rpc GetFlagTreatment (FlagRequest) returns (FlagReply );
  rpc TrackEvent       (EventInfo  ) returns (TrackReply);
}

// The request message containing the feature flag name and attributes.
message FlagRequest {
  string flagName = 1;
  map<string, string> attributes = 2;
}

// The request message containing the event info.
message EventInfo {
  string eventType = 1;
  double value = 2;
}

// The response message containing the feature flag treatment.
message FlagReply {
  string treatmentResult = 1;
}

// The response message containing the boolean value returned from the Track function.
message TrackReply {
  bool isEventTrackedSuccessfully = 1;
}